### ISSUE TITLE
Change "gardenName" to "name" in Gardens model

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#11]
Change gardenName to name in the Gardens model. Rerun makemigrations and migrate, ensure that any mention of gardenName is changed to garden.name in the entire codebase.

**Comment by Hinal-Srivastava** [comment]
I'll do it.👍

**Comment by sachajoy** [comment]
@capndave assign it to me

**Comment by Hinal-Srivastava** [comment]
@capndave is assignment required?

**Comment by capndave** [comment]
@sachajoy - It looks like @Hinal-Srivastava is working on it, would you like to take on [#12](https://github.com/capndave/gardenbuilder-backend/issues/11) instead?

**Comment by capndave** [comment]
@Hinal-Srivastava you can go ahead, but I'll assign it to you.

**Comment by Hinal-Srivastava** [comment]
> @Hinal-Srivastava you can go ahead, but I'll assign it to you.

Cool. On it🤘🏼
