### ISSUE TITLE
Change "gardenName" to "name" in schema.py in the Gardens app. 

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#12]
## Todo

- Change "gardenName" to "name" in schema.py in the Gardens app.
- Test that all garden-related queries and mutations still work. 
- Run tests to ensure that any related tests still pass, update tests if needed.

## Before Starting

Ensure that [#11](https://github.com/capndave/gardenbuilder-backend/issues/11) is completed first!

**Comment by sachajoy** [comment]
@capndave can i take this issue

**Comment by sachajoy** [comment]
this for hacktoberfirst issue right

**Comment by capndave** [comment]
Sure, any of them are for Hacktoberfest, really
