### ISSUE TITLE
Change "bedName" to "name" in Beds model

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#13]
Change bedName to name in the Beds model. Rerun makemigrations and migrate, ensure that any mention of bedName is changed to bed.name in the entire codebase.

**Comment by sachajoy** [comment]
@capndave assign me this issue

**Comment by sachajoy** [comment]
do we have to do it in postgresql or can we use mysql

**Comment by capndave** [comment]
By now you've already made the updates, did you use mysql? If so I can probably remove the bit about installing postgres from the docs. I use postgres on my local and in production
