### ISSUE TITLE
Update resolve_gardens in gardens/schema.py to throw an error unless user is_staff or is _superuser

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#17]
Please update `resolve_gardens` (at line 40) in `gardens/schema.py` to throw an error unless user `is_staff` or `is _superuser`. You can check out the `resolve_user_gardens` resolver for some clues as to how to do so.

**Comment by iamlordutkarsh** [comment]
We Have To use if condition To define it , if user is is_staff or is_superuser then proceed else throw an Error ?

**Comment by StatingPrism** [comment]
@capndave, May I have this issue assigned to me?

**Comment by StatingPrism** [comment]
Request to close? @capndave

**Comment by capndave** [comment]
Thanks @StatingPrism, I'm closing now. @iamlordutkarsh pardon the delay on getting back to you!
