### ISSUE TITLE
Write resolve_beds_for_user resolver in beds/schema.py

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#21]
The query needs to:

- Only return beds associated with the requesting user (from `info.context.user`)
- Accept an optional gardenId parameter
- If the gardenId argument is passed, then only return the beds associated with that garden

**Comment by JuliusChrona** [comment]
@capndave Hello,
digitalocean make new rule about participation in Hacktoberfest (https://twitter.com/hacktoberfest/status/1312221208667185153)

So may you add the "hacktoberfest" topic to repository? ^_^

**Comment by capndave** [comment]
@JuliusChrona Thanks for the heads up, I added the hacktoberfest topic
