### ISSUE TITLE
Add login routine to CreateUser mutation in users/schema.py

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#22]
Update the CreateUser mutation so that a newly-created user is also authenticated, and a JWT (JSON web token) is returned to the client with the graphql response, much like occurs with the `tokenAuth` mutation.

**Comment by AyonPal** [comment]
I'd like to work on that issue

**Comment by AyonPal** [comment]
@capndave , i made a pr that fix this issue. Don't think any testcase needed. Can you please review?
