### ISSUE TITLE
Set up way to automatically deploy to google cloud on commit

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#30]
## Type
Feature request

## Problem or To-Do
There needs to be a streamlined way to push this to Google Cloud when `master` is updated. I don't know the best, simple tool to do this so any input is appreciated. Ansible? A Bash script?

**Comment by rexdivakar** [comment]
I would love to work on it @capndave 
Also i would need the credentials to setup things on ur google cloud engine platform

**Comment by capndave** [comment]
@rexdivakar what's your email address? I'll see about giving you your own credentials for the bucket that this runs on, and the database. I have things set up for me to do quick deploys with `gcloud app deploy`, but that's not automated in any way.

**Comment by rexdivakar** [comment]
Pls respond once u mailed me @capndave   rexdivakar@gmail.com

**Comment by capndave** [comment]
You should have just received an email from google

**Comment by rexdivakar** [comment]
yeah got it will raise a PR soon as i complete it

**Comment by rexdivakar** [comment]
Can u please assign it to my name also add a Hacktoberfest tag so its helpful for me !! @capndave

**Comment by rexdivakar** [comment]
I need access to ur github repo also permission to access it via google cloud for deploying it 

![image](https://user-images.githubusercontent.com/15235122/95147604-d41f9980-079e-11eb-85ee-c0b4ae98887d.png)

**Comment by capndave** [comment]
Ok you should already have permission to deploy on google cloud and I just added you as a collaborator to this repo

**Comment by capndave** [comment]
You should be able to add this as a `push` stage routine in `.pre-commit-config.yaml`

**Comment by rexdivakar** [comment]
great will work on it now

**Comment by rexdivakar** [comment]
![image](https://user-images.githubusercontent.com/15235122/95337081-1ea03380-08cf-11eb-827c-a641ecc83094.png)
Still i'm unable to get access can u pls check ?

**Comment by capndave** [comment]
@rexdivakar I looked into this today and due to the many permission-related steps required, I decided that I should go ahead and do it. So I did! Pushes to the master branch now deploy the app to google cloud. Thanks so much for working on this, I look forward to your other contributions! Next step is ensuring that the test suite and linting works correctly via Github Actions. I'll work on that as well.

**Comment by capndave** [comment]
@rexdivakar I figured out the basic flow for this, using Google Cloud Build. Unfortunately it requires that you hard-code environment variables/credentials into your `app.yaml` file, which I don't want to share on github. I guess I'll have to do deployments to production manually on my side :shrug:
