### ISSUE TITLE
Add `description` property/field to the Bed model in beds/model.py

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#48]
## Type
Feature request

## Problem or To-Do
Add `description` property/field to the `Bed` model in `beds/model.py`. Make it a non-required string/text field of maximum length 60 characters. 

If you would, please also add a test to `beds/tests.py` that tests to ensure the object includes a `description` property.

**Comment by Kirkkm** [comment]
Hey @capndave , could you assign this to me? I can take a look at this.

**Comment by capndave** [comment]
@phayaran I'm assigning this to @Kirkkm since he asked first! In the future please pipe up here before submitting a pull request.

**Comment by Kirkkm** [comment]
@capndave Sorry for the delay, but I will start working on this here soon. Had work stuff and another Hacktoberfest issues to finish up delay me a bit.
