### ISSUE TITLE
Add clear guidelines to CONTRIBUTING.md to make it clear that a contributor must be assigned to an issue before submitting a pull request

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#53]
## Type
Documentation update

## Problem or To-Do
Add clear guidelines to CONTRIBUTING.md to make it clear that a contributor must be assigned to an issue before submitting a pull request. The only exception to this rule should be for minor documentation updates. Feel free to word this however you feel is appropriate, capndave will review. Thanks!

**Comment by saurabhhere** [comment]
@capndave Have a look at PR.
