### ISSUE TITLE
Take contributing guidelines out of README.md and add a link to CONTRIBUTING.md in README.md

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#54]
## Type
Documentation update

## Problem or To-Do
Take contributing guidelines out of `README.md` and add a link to `CONTRIBUTING.md` in `README.md`. If it's possible to instead embed the contents of `CONTRIBUTING.md` in `README.md` (via a link of some sort) please do that instead.

**Comment by jennifergreeneyes** [comment]
Hi Dave, I will give this a go?

**Comment by saurabhhere** [comment]
Hi, @capndave  can you assign this issue to me?
