### ISSUE TITLE
Pytest fails on tests for apps/sections/tests.py

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#55]
## Type
Bug Report

## Problem or To-Do
I'm getting errors on `test_sections_query_without_data` and `test_sections_query_with_data`. Both throw and error similar to

```bash
E       TypeError: object of type 'NoneType' has no len()
apps/sections/tests.py:91: TypeError
```

@Ryan104 originally was kind enough to write these tests. Please take a look and troubleshoot!

**Comment by Ryan104** [comment]
Hey @capndave I'll look into this one!
