### ISSUE TITLE
Set up Github Actions with Linting and Unit Tests

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-backend#8]
have it run linter and unit tests before accepting pull requests

**Comment by andrew-the-drawer** [comment]
Hi there, I would love to take this issue. Can you assign it to me? Tks a lot! 

cc: @capndave

**Comment by capndave** [comment]
You may need to be a collaborator on this repository to do that. Let me know if you need to be added.

**Comment by andrew-the-drawer** [comment]
@capndave tks a lot. Lemme try to set up on my forked repo first.

**Comment by andrew-the-drawer** [comment]
Please consider my newest PR #45 @capndave. Thanks a lot
